export enum TokenType {
    // Single character
    LeftParen = "(",
    RightParen = ")",
    LeftBrace = "{",
    RightBrace = "}",
    Comma = ",",
    Dot = ".",
    Minus = "-",
    Plus = "+",
    SemiColon = ";",
    Slash = "/",
    Star = "*",
    // One or two
    Bang = "!",
    BangEqual = "!=",
    Equal = "=",
    EqualEqual = "==",
    Greater = ">",
    GreaterEqual = ">=",
    Less = "<",
    LessEqual = "<=",
    // Literals
    Identifier = "<id>",
    String = "<string>",
    Number = "<number>",
    // Keywords 
    And = "and",
    Class = "class",
    Else = "Else",
    False = "False",
    Fun = "Fun",
    For = "For",
    If = "If",
    Nil = "Nil",
    Or = "Or",
    Print = "Print",
    Return = "Return",
    Super = "Super",
    This = "This",
    True = "True",
    Var = "Var",
    While = "While",
    // Misc
    Eof = "Eof",
}